apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-defrag-job
spec:
  template:
    spec:
      containers:
      - name: etcdctl
        image: <registry>/k8s/etcd:latest@sha256:a447e62a370e157ab5448d90352cdf8da21e280b4eca4ff0c0710cd774589aa8
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: GREETING
          value: "Hello, that is defrag pod"
        command:
        - /bin/sh
        - -c
        args:
        - echo $GREETING; etcd_host=`cat /home/hosts | awk '{print $1}' | tail -n 1`; etcdctl='etcdctl  --insecure-transport=false --insecure-skip-tls-verify --cacert=/home/kubernetes/static-pod-resources/configmaps/cloud-config/ca-bundle.pem --cert=/home/kubernetes/static-pod-resources/etcd-certs/secrets/etcd-all-peer/etcd-peer-master-01.crt --key=/home/kubernetes/static-pod-resources/etcd-certs/secrets/etcd-all-peer/etcd-peer-master-01.key';
          MEMBERS=`$etcdctl --endpoints="https://${etcd_host}:2379" member list |  awk 'BEGIN { ORS=" " }; { print $5 }' | sed -e 's/,//g')`;
          for i in $MEMBERS;
          do
            $etcdctl --endpoints="${i}" defrag;
          done;
          sleep 1000;
        volumeMounts:
        - mountPath: /home
          name: etcd-certs
      volumes:
      - name: etcd-certs
        hostPath:
          path: /etc/
      restartPolicy: OnFailure
      nodeSelector:
        etcd: "true"
